export default {
  "6" : "catch",
  "7":  "dodge",
  "10":  "foulAppearance",
  "18": "alwaysHungry",
  "19":  "regeneration",
  "20":  "takeRoot",
  "26":  "dauntless",
  "31":  "boneHead",
  "47":  "pass",
  "50": "pro",
  "51":  "reallyStupid",
  "55":  "shadowing",
  "60":  "sureFeet",
  "61":  "sureHands",
  "67":  "unchannelledFury",
  "69":  "tentacles",
  "77":  "stab",
  "78":  "hypnoticGaze",
  "84":  "animalSavagery",
  "86" : "animosity:all",
  "87" : "timber",
  "95" : "projectileVomit",
  "98" : "animosity:dwarfHalfling",
  "99" : "animosity:dwarfHuman",
  "100" : "animosity:orcLineman",
  "101" : "animosity:orcBigUn",
  "102" : "animosity:underworldGoblin",
  "1008" : "loner",
  "1020" : "plagueRidden",
  "1022" : "tentacles",
}
